---

- name: RESTIC AWS | Configure environment
  template:
    src: home/restic/aws_restic.env.j2
    dest: /home/restic/.restic.env
    owner: restic
    group: restic
    mode: 0400

- name: RESTIC AWS | Configure bashrc
  lineinfile:
    path: /home/restic/.bashrc
    line: "source /home/restic/.restic.env"
    state: present
